const quotes = {
"Mikayla and Dr. Steward": ["I am not good with words; Get better", ""],
"Mick W": ["If you need a hype man, you'll never be successful.", "Why does the field look like the French flag?", ""],
"Cale W": ["I don’t know how to use my fingernails!", "What is your favorite KT-extinction animal?", "If I were in the Tour de France it wouldn’t be called the Tour de France it would be called the tour of eat my dust", "My hair smells like panda express", "It was a good thing the Baltimore Bridge collapsed", "My wife went out :(", "The F in John F. Kennedy stands for fortnight. John Fortnight Kennedy!", "Hogwarts is the illuminati of the wizarding world.", ""],
"Vienna R": ["Don’t judge us, it wasn’t a group decision. ", "That's so crescendo", "Are you [Jackson D] cosplaying as Matthias?", "Are you in your misogynist era Andrew?!?", "It's like how you're illiterate, I can't call 911", "I've used chopsticks to eat yogurt", "Aneesh is unique, we cannot recreate aneesh", "If Meabh murdered you (Andrew), I still wouldn't kick her off of the subteam.", "If Micah can break it, we're cooked ", "There's nothing there. It's empty (points to bicep)", "You [Hannah K] think Limelight is the root of all evil", "Hanna, you can't scare the children", "It’s still pronounced “chute” not “trap”", "Your mouth smells good. What are you eating?", "Everything Micah says, I would wear on a shirt", ""],
"Morgan D": ["Youre like an onion, but in the shrek kind of way.", "Of all the places to lick me, why my shoulder?", "I should really start paying more attention to the amount of loctite I'm consuming", "If I'm Dean Kamin, I think I'm allowed to be sassy", ""],
"Sarah Y": ["I wish someone would quote meeeee!", "High School is fun except for the school part ", "Kanye was right!", "We are a group. We rise together, we fall together. And I’m the only one falling right now!", "Wait can somebody quote me? Someday? I just want to be quoted", "That was me", "I like how you called me a monster ", "I thought there were only 3 countries... The US, China, and the UK", "Should I just join the boys track team?", "My chicken looks like a bird…", ""],
"Micah S": ["Every time you’re using spacers you’re wasting time. (2nd in a series)", "Tap Magic is the magic the Hole Wizard uses", "We don’t need no Becky round here (in a western accent)", "I’m gonna quit the team if we win spirit award", "Corners don't exist", "Ya we slayyeddd", "I'm awake to the real world. My eyes have been opened. And my head hurts", "We like blacks. Don’t quote me.", "We’re going to be cooked", "Mick did you kill him? Oh-", "Good night Lyra … and everyone else", "Optimism is what leads to failure", "Communism is good, because it ends in a dictatorship.", "Why waste your time being sad?", "I'm awake to the real world. My eyes have been opened. And my head hurts", "I don't know what they do with cancer but they do it", "This one looks more Korean than the other", "I don't know how big numbers work", "Maybe the real CADathon was the friends we made along the way", "Getting your battery out of your robot doesn’t score you any points ", "Meat is fruit and vegetables ", "If you were good enough you would build hopper walls so you wouldn’t miss", "If you can’t CAD at 2 am, you can’t CAD at all", "I disagree. You're wrong. ", ""],
"Mr. Hascall": ["3 trolls movies is 4 too many", "*Imitating Shreya* My eyes are more important that yours, chetas", "People have names Anton", "Directions are what you follow when all else fails.", ""],
"Jackson D": ["Don't worry I'll be your mother!", "I've dipped my toes in Taylor Swift!", "Henry Kellen is soooo hot", "(Asking Lyra about Abby) Is that your MOM?!", "“I wanna hear Mick’s scream” ", "A pulled pickle sandwich? Of course I want a pulled pickle sandwich!", "Tables are beautiful, don't be a hater", "Xmobile is coming for the ducks ", "Thank you!!! At least someone hates me!!", "All cookies are 3D", "I wonder what these taste like", "If we’re gonna make a turret, we shouldn’t make it bad", "This is dramatic, inspiring classical music. If you have a problem with it, go back to controls", "This thread lock is misunderstood ", "Nooo the bolt isn't real either!! ", "I would smell markers in the back of health class", "3/8 is an imaginary number I don't believe exists", ""],
"Michael H": ["Thanks for talking about my body", "Why do you keep trying to get me to go on a date with you [Adam]? He’s asked me on a date two times already! He’s staring longingly at me! ", "I got a victory royale, right kids? Poggers.", ""],
"Meabh H": ["*Adam drops goldfish* Is it smiling back?", ""],
"Grace C": ["(whispered) Stop it, you're weird", "I don’t know the national anthem. Is that the one that starts with ‘We the People’?", "I don’t know the national anthem. Is that the one that starts with ‘We the People’?", ""],
"Anika S": ["You kind of remind me of Batman's butler, Albert", "I like the womb thing.", "Anirudh can you say something interesting ", "Now you're going to un-regress... you're going to gress.", ""],
"Owen M": ["I know a bit about leadership, I'm the drop leader for my Fortnite squad.", "You're not an oxymoron, you're just a regular moron", "The day that Costco raises the price of rotisserie chicken is the day I will rebel against the government ", ""],
"Chloe L": ["Women in STEM! Plus Andrew !", ""],
"Becky M": ["Toxicity!!!!! We love it.", "I forgot that wrenches were two-sided", "Leave your shirts on please", "Could we just get rid of team neutrino as a whole?", "The instructions were telling me things that I didn’t want to do", "Mikayla, that why you don’t hammer your fingers! You go deaf!", "Elijah! You can't take a sledgehammer to a small person!", "You can slap people with this", ""],
"Elijah S": ["They should start flavoring tools", "I got pulled over and shot at by the police while wearing the neutrino logo!", ""],
"Chetas A": ["Don't quote me on that!", "Accept my pull request or I will murder you!", "Smart enough to design a robot, not smart enough to assemble it", "That moves!?  I’m so stupid!", "Smart enough to design a robot, not smart enough to assemble it", "Well that seems like a controls problem", "I don't like Vienna anymore. It's vertices", "We don't make money, we just spend it. ", "Since when is Halloween a holiday?", "I rather be called a slur than be called arch", "Why isn’t 10 divisible by 6?", "Reality is more real than CAD. ", "If you die it’s a skill issue", ""],
"Laura W": ["You look like a tree!", "Can I make lily shorter?", "It froze! I just bit into a tomato Popsicle!!!", ""],
"Anton L": ["There’s the big half inch and the small half inch", "I found multiple dead bunnies in my hose", "We do not like success here on Team Neutrino.", "Saudi Arabia is shaped like a rhinocerotops", "Matthias should become our mascot", "2306 is the opposite of empty ", ""],
"Matthias R": ["It’s the mamba mentality", "My ideal posture is that of a croissant ", "My ideal posture is that of a croissant ", "[holding a file] Do you need to be filed, Jackson?", ""],
"Sun Tzu": ["Know thy self, know thy enemy. A thousand battles, a thousand victories.", "If you know the enemy and know yourself, you need not fear the result of a hundred battles. If you know yourself but not the enemy, for every victory gained you will also suffer a defeat. If you know neither the enemy nor yourself, you will succumb in every battle.", ""],
"Dr. Steward": ["Why does everybody talk about how much they are going to miss Micheal Holm when he graduates, and nobody is saying how much they will miss me when Dr. Steward dies?", "“We all have issues.", "Battle bots is the pro wrestling of robots", "I can be micah. *mimicks* you can’t do that!!", "I don’t think you [Jackson D] need to worry about being too smart", "You've discovered the foundation of youth--its loctite", ""],
"Logan M": ["I'd rather eat some bedazzled trash than normal trash y'know what I'm saying", "Bada bing bada boom hammer and sickle ", "Hotdog is the species, the sandwich is the genus", "Maddie could be a pterodactyl right now and I could be the only one to not see it ", ""],
"Andrew G": ["Hey Dagney, we just dominated all these children. Good job :D", "It's more interesting when everything's broken", "That's a massive apple, you'll never need to see a doctor again.", "Adam isn't real, Adam is a ghost ", "Adam isn't real, Adam is a ghost ", "Aaaaaaaarrrrrg", "Ur mom is hot", "Have you tried cocaine??", "If you eat my heart you gain my powers", "Looks like I'm the pregnant one ", "I'm not funny irl ", "Move, I'm competent!", "Is it really sweating if you don't smell?", ""],
"Leslie K": ["Don't fear! We're not broke... I think", "Now I can touch Andrew’s keyboard with my grimy, greasy hands!", "I’m not feeling Gucci I’m more like Versace ", "Have you ever seen stupidity evolve? Darwinism is going the wrong way. ", "I dont want to look like I've committed a murder!", "Magic the Gathering— is that a teenage experience that everyone should have like parties and drugs?", ""],
"Henry K": ["I have a playlist dedicated to the moon", "You’ve got to take over my job of doing whatever Becky tells me to do. ", "That’s like if I found your arm on the ground and said ‘Hi Becky’", ""],
"Lyra H": ["When solid works is not behaving take it behind the barn and shoot it. ", "Don’t use babies as life preservers", "I’m gonna create child sized armor… toddler fight club", "Building the field is worse than building a robot", "Is being an Engineer just being a Units Rancher?", "they stole my credit card information- of course I'm malicious!!!", "Sorry, he's (my dad) built different", "I can respect Skibidi Toilet", "Culver’s is more important than listening to your parents", ""],
"Sherry W": ["Children are objects", "Is that a slack logo? *points to a church*", "*says to micah* Im wearing a neutrino hoodie Im more holy than you!", ""],
"Josiah S": ["Im gonna leave that to a self-proclaimed smart person", "Remind me to never pet the inside of a turtle’s mouth. ", ""],
"Matthew H": ["There are 171,716 something words in the English dictionary but none of them describe how much I wish to bellyflop on a bed of nails.", ""],
"Shreya S": ["“let me cook”", "Oh my god its only six!!!", "I'm always Hitler", "Safety glasses hurt my eyes", "Can they discriminate based on race again? I want them to!", "Wait turkey is middle eastern.. you're the one is honors world studies ", "Do you wear a toupe? ", "Hey, move your [Chetas's A] grimy fingers!", "Safety glasses hurt my eyes", "You said you didn't like me in secret- I'm confronting you", ""],
"Aneesh S": ["The real lasagna is the friends we made along the way.", ""],
"Andrew + John": ["Andrew: Do we have gravity?   John: Yes, we will be doing the climb on Earth. ", ""],
"Lovie + Mick": ["Lovie: I got an email that I ran out of print credits. ... Mick: Yeah. You have like 5.", ""],
"Moriah Z": ["You are just sooo punchable!", ""],
"FDR": ["When you reach the end of your rope, tie a knot in it and hang on.", "The only thing we have to fear is fear itself.", ""],
"Bill Clinton": ["Being president is like running a cemetery: you’ve got a lot of people under you and nobody’s listening.", ""],
"Herbert Hoover": ["Blessed are the young, for they will inherit the national debt.", ""],
"Carrie Fisher": ["Instant gratification takes too long.", ""],
"Ellen DeGeneres": ["Accept who you are. Unless you’re a serial killer.", ""],
"Will Ferrell": ["Before you marry a person, you should first make them use a computer with slow Internet to see who they really are.", ""],
"Oscar Wilde": ["The man who says his wife can’t take a joke, forgets that she took him.", "Always forgive your enemies; nothing annoys them so much.", ""],
"Emperor Hirohito of Japan": ["The fruits of victory are tumbling into our mouths too quickly.", ""],
"Napoleon Bonaparte": ["Never interrupt your enemy when he is making a mistake. *its also gracious professionlisim*", ""],
"No one ever": ["PID is easy. I wrote it last night.", ""],
"Milton Friedman": ["Nothing is as permanent as a temporary solution that works *random reditor: I’m pretty sure the entire country of Belgium was built on that principle*", ""],
"Nelson Mandela": ["It always seems impossible until it's done.", ""],
"Anonymous": ["The tassel was worth the hassle.", ""],
"Mark Twain": ["The two most important days in your life are the day you are born, and the day you find out why.", ""],
"Kevin Hart": ["I gotta stop saying how stupid could you be? I'm beginning to feel like people are taking as a challenge", ""],
"MLK": ["I have a dream...", ""],
"Abraham Lincoln": ["Four score and seven years ago our fathers brought forth, upon this continent, a new nation, conceived in liberty, and dedicated to the proposition that all men are created equal.", ""],
"JFK": ["Forgive your enemies, but never forget their names.", ""],
"Barack Obama": ["Why can't I just eat my waffle?", ""],

"Joe Montana": ["Winners, I am convinced, imagine their dreams first. They want it with all their heart and expect it to come true. There is, I believe, no other way to live.", ""],
"George W. Bush": ["I know the human being and fish can coexist peacefully", ""],
"Maddie L": ["GET IN THE BANANA!", "Pull me around like one of your French girls, Morgan", "The date of today is yesterday and the date of yesterday is today", "The date of today is yesterday and the date of yesterday is today", ""],
"The guy who offered Leslie a beer": ["You guys are way smarter than me", ""],
"Swaran P": ["*to Anirudh* My mom would adopt you", ""],
"Karthik Kanagasabapathy": ["Soft is not an insult. It is a blanket, and people like blankets. ", ""],
"Lovie R": ["Truckers do destroy toilets ", ""],
"Joy Z": ["China is the Asia of Asia ", "China is the Asia of Asia ", "I am not a indpendent woman, I'm a DEpendent woman", "There's different levels of how similar you look to Dr. Steward", ""],
"Olivia Z": ["William McDeid McDied while eating McDonald’s ", "Bronny threw the ball too hard", "Papa pass me the ball! (what Olivia thinks Bronny James says to his dad, LeBron James, when they play together on the Los Angeles Lakers and Bronny's open)", "On a scale of 1 to plumber, how badly do you want to drop out of school?", "It’s not my moment of truth, it’s my moment of weakness and failure", "Olivia, what are you doing?, I'm peering over your shoulder to read your emails", "William McDeid McDied while eating McDonald’s ", "I just want to play Party Rock Anthem at my funeral", "You can quantify anything if you try hard enough", ""],
"Lily F": ["Dagney cried, what about you ", "I'm Rayn Forbes, a sophomore ", "FIVE BOOMS FOR HIS DEATH BROTHER!!", "My first ever rivet. It was a riveting experience.", "you should choose Olivia's quote ", "At team Neutrino, we spread cancer ", "What's your nationality? I say Anika ", "A new opportunity to make memes? Sounds good to me!! ", "Dagney cried, what about you ", "Where's the bread??? I feel disrespected as a person ", "I'm Rayn Forbes, a sophomore ", "Is this the era of Dagney crying quotes?? Like what's happening ", "If you were a feature in OnShape, what would you be? I’d be a center-point circle", "I think we should make a robot that can frack oil", ""],
"Lynda S": ["Why is it [the forbidden parmesan] forbidden?", "Wait- do you know this woman on the Internet? She just gave birth! Her baby is born! ", "0/0 is 100% of zero", ""],
"William M": ["I don't like penn state ", "LeBron is not a person he is a diety ", "I'm chalant and I'm proud", "LeBron!!", "Men in STEM", ""],
"Lyra h": ["When solid works is not behaving take it behind the barn and shoot it. ", "Don’t use babies as life preservers", "I’m gonna create child sized armor… toddler fight club", "Building the field is worse than building a robot", "Is being an Engineer just being a Units Rancher?", "they stole my credit card information- of course I'm malicious!!!", "Sorry, he's (my dad) built different", "I can respect Skibidi Toilet", "Culver’s is more important than listening to your parents", ""],
"Shreya [to John]": ["I thought you were 47", ""],
"Yehang C": ["I didn't loose it, I just didn't find it today ", "Wait where is Adam?? Where did my father go?", ""],
"Laura C": ["Laura!!?", "I feel... I feel like.... Actually, I have no feelings-", ""],
"Archer N": ["Yesss I knew it.", "What's the difference between can be and is", "Anything written on the side of a gas station is true, as long as it looks professional enough ", "No, we don't *need* a robot, we *want* a robot.", "Things are thinging", ""],
"Fyona S": ["Money", ""],
"Hanna K": ["Dab me up wifey", "Everyday I colonize my mother.", "I know you have a rubber band compartment, I just don’t know where it is!", "If you ghost write your memoir, its a bibliography.", "It isn't more work if the current work isn't working ", ""],
"Anirudh M": ["I don't want anyone to hear me", "Those song are too popular, I can't be liking them. ", "The less you check slack, the better.", ""],
"Someone": ["No kids are going to the ER today", "Trdddvbjiudd", ""],
"Maddie [to Elijah]": ["Are you an edge lord?", ""],
"John H": ["*airquotes* it's not a dog ", "Depression is like toast, there are different levels of darkness", ""],
"Hanna to Yehang": ["Yes wifey!", ""],
"Sisis": ["Isosososos", ""],
"Allen C": ["We gave them away so that other people could tie up kids", "We're just farming quotes now.", "I like my candy 99% cocaine ", ""],
"Lily C": ["We spread Nutella, not Neutrino.", ""],
"Anika and Sarah": ["If we win chanmps we shall shaveeth our heads", ""],
"Chetas a": ["Don't quote me on that!", "Accept my pull request or I will murder you!", "Smart enough to design a robot, not smart enough to assemble it", "That moves!?  I’m so stupid!", "Smart enough to design a robot, not smart enough to assemble it", "Well that seems like a controls problem", "I don't like Vienna anymore. It's vertices", "We don't make money, we just spend it. ", "Since when is Halloween a holiday?", "I rather be called a slur than be called arch", "Why isn’t 10 divisible by 6?", "Reality is more real than CAD. ", "If you die it’s a skill issue", ""],
"Dagney P": ["Fashioned is old-fashioned", ""],
"Rayn K": ["Our goal is to make Dagney cry", ""],
"Rayn and lily": ["We need Dagney to cry", ""],
"Trent to Nathan": ["According to panda express it's the food of your people", ""],
"Trent A": ["I have other mental issues", ""],
"Seonu S": ["It’s constructive beefing", "Keep your heads high and feet low. ;)", ""],
"David R": ["Your fingers look like petite carrots ", ""],
"Jackson": ["Can I un-unionize them?", ""],
"Claire W": ["I'm not Gen Alpha! I'm 29", ""],
"Alex M": ["Archer has the potential to be a pizza", ""],
"Lily to Chetas": ["You’re literally our leader, why are you gatekeeping?", ""],
"Rosalie W": ["42 zip ties is enough for a zip code ", ""],
"Siwon P": ["Better to be late than early.", ""],
"Andrew": ["Shouldn't *you* [Allen C] know Chinese Remainder Theorem?", ""],
"Harrison C": ["That’s like ancient Indian Basketball (about Rebuilt)", ""],
"Muyao W": ["What is that, some kind of mating ritual?", "I'm not Spanish ", ""],
"Uliana M": ["La Croix is like drinking TV static", " [after hearing about deer pancreas] There are too many delicacies in this world!", ""],
"Lily F and Chetas A": ["[Chetas] is against women in STEM. No, I’m against YOU in STEM.", ""],
"Alex R": ["Maybe we DO need to wear hard hats.", ""],
};

function getQuote() {
  let keyList = Object.keys(quotes);
  let amountOfKeys = keyList.length;
  let keyNumber = getRandomInt(0, amountOfKeys);
  let personQuoteList = quotes[keyList[keyNumber]];
  let quote = personQuoteList[getRandomInt(0, personQuoteList.length-1)];
  let wordCount = quote.split(' ').length-2;
  let quotePackage = [quote, "-" + keyList[keyNumber], ((0.45*wordCount))*1000];
  return quotePackage;
}

function getRandomInt(min, max) {
  const minCeiled = Math.ceil(min);
  const maxFloored = Math.floor(max);
  return Math.floor(Math.random() * (maxFloored - minCeiled) + minCeiled); // The maximum is exclusive and the minimum is inclusive
}
